rules:
  indent:
    - 2
    - tab
  quotes:
    - 2
    - single
  linebreak-style:
    - 2
    - unix
  semi:
    - 2
    - never
env:
  es6: true
  node: true
  browser: true
  jquery: true
globals:
    moment: true
extends: 'eslint:recommended'
